name: Build
on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 17

      - name: Touch local properties
        run: touch local.properties

      - name: Check formatting
        run: ./gradlew :app:spotlessCheck
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 17

      - name: Touch local properties
        run: touch local.properties

      - name: Run linter
        run: ./gradlew lintDebug
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}

      - name: Upload Build Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/lint-results-debug.html

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Touch local properties
        run: touch local.properties

      - name: Run Unit Tests
        run: ./gradlew test
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/